from Token import REGISTER, IMMEDIATE, OPEN_SQUARE, CLOSE_SQUARE, LABEL

INSTRUCTION_SET = {
    "add": (REGISTER, REGISTER, REGISTER),
    "addi": (REGISTER, REGISTER, IMMEDIATE),
    "stur": (REGISTER, OPEN_SQUARE, REGISTER, IMMEDIATE, CLOSE_SQUARE),
    "ldur": (REGISTER, OPEN_SQUARE, REGISTER, IMMEDIATE, CLOSE_SQUARE)
}